<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <title><?= $titulo ?></title>
</head>
<body class="bg-light">
<div class="container my-5 text-center">
    <div class="py-5">
        <i class="bi bi-check-circle-fill text-success" style="font-size: 5rem;"></i>
        <h1 class="fw-bold mt-3">Obrigado pela sua compra!</h1>
        <p class="lead text-muted">O seu pedido foi confirmado com sucesso.</p>
        
        <div class="mt-4">
            <a href="<?= BASE_URL ?>/home" class="btn btn-primary btn-lg">Voltar para a Loja</a>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>